# Generated by Django 5.1.6 on 2025-03-27 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='grade',
            field=models.CharField(default='Not Assigned', max_length=10),
            preserve_default=False,
        ),
    ]
